theme: jekyll-theme-architect
title: Développement d'applications mobiles avec Ionic 3
description : Créez efficacement des applications mobiles multiplateformes avec Angular, ReactJS ou VueJS
paginate: 5

plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-seo-tag
   - jekyll-sitemap
   - jekyll-avatar
   - jekyll-include-cache
